import { Octokit } from "@octokit/rest";
import type { AgentProposal } from "./types";

const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
const owner = process.env.GITHUB_OWNER!;
const repo = process.env.GITHUB_REPO!;
const baseBranch = process.env.GITHUB_BASE_BRANCH ?? "staging";

export async function createProposalPR(proposal: AgentProposal): Promise<string> {
  const timestamp = Date.now();
  const branch = `ux-agent/proposal-${timestamp}`;

  const { data: base } = await octokit.repos.getBranch({ owner, repo, branch: baseBranch });
  const baseSha = base.commit.sha;

  await octokit.git.createRef({
    owner,
    repo,
    ref: `refs/heads/${branch}`,
    sha: baseSha,
  });

  for (const change of proposal.changes) {
    let existingFileSha: string | undefined;
    try {
      const { data } = await octokit.repos.getContent({ owner, repo, path: change.path, ref: branch });
      if (!Array.isArray(data) && data.type === "file") {
        existingFileSha = data.sha;
      }
    } catch {
      // file doesn't exist yet, that's fine
    }

    await octokit.repos.createOrUpdateFileContents({
      owner,
      repo,
      path: change.path,
      message: `ux-agent: update ${change.path}\n\n${change.reasoning}`,
      content: Buffer.from(change.content).toString("base64"),
      branch,
      ...(existingFileSha ? { sha: existingFileSha } : {}),
    });
  }

  const insightsList = proposal.analyticsInsights.map((i) => `- ${i}`).join("\n");
  const changesList = proposal.changes
    .map((c) => `### \`${c.path}\`\n${c.reasoning}`)
    .join("\n\n");

  const { data: pr } = await octokit.pulls.create({
    owner,
    repo,
    title: `[UX Agent] Proposal ${new Date(timestamp).toISOString().slice(0, 10)}`,
    head: branch,
    base: baseBranch,
    body: `## Summary\n\n${proposal.summary}\n\n## Analytics Insights\n\n${insightsList}\n\n## Changes\n\n${changesList}\n\n---\n_Generated by the UX optimization agent based on real user behavior data._`,
  });

  return pr.html_url;
}
