import { Octokit } from "@octokit/rest";
import { createClient } from "@insforge/sdk";
import { takeScreenshot } from "./screenshot";
import { searchCodebase } from "./nia";
import type { AnalyticsSummary } from "./types";

const insforge = createClient({
  baseUrl: process.env.INSFORGE_URL!,
  anonKey: process.env.INSFORGE_API_KEY!,
});

const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
const owner = process.env.GITHUB_OWNER!;
const repo = process.env.GITHUB_REPO!;
const PROD_URL = process.env.PROD_URL ?? "https://team-snorlax.vercel.app";

async function pollForPR(createdAfter: number, timeoutMs = 900000): Promise<number> {
  const start = Date.now();
  console.log("   Polling every 20s...");
  while (Date.now() - start < timeoutMs) {
    const { data: prs } = await octokit.pulls.list({
      owner, repo, state: "open", sort: "created", direction: "desc", per_page: 10,
    });
    const pr = prs.find(
      (p) =>
        (p.head.ref.startsWith("ux-agent/") || p.head.ref.startsWith("devin/")) &&
        new Date(p.created_at).getTime() > createdAfter
    );
    if (pr) {
      console.log(`   Found PR #${pr.number}: ${pr.title}`);
      return pr.number;
    }
    process.stdout.write(".");
    await new Promise((r) => setTimeout(r, 20000));
  }
  throw new Error("Timed out waiting for Devin to open a PR");
}

async function pollForPreviewUrl(branch: string, timeoutMs = 300000): Promise<string | null> {
  const start = Date.now();
  while (Date.now() - start < timeoutMs) {
    const { data: deployments } = await octokit.repos.listDeployments({
      owner, repo, ref: branch, per_page: 5,
    });
    for (const dep of deployments) {
      const { data: statuses } = await octokit.repos.listDeploymentStatuses({
        owner, repo, deployment_id: dep.id, per_page: 5,
      });
      const ok = statuses.find((s) => s.state === "success" && s.environment_url);
      if (ok?.environment_url) return ok.environment_url;
    }
    process.stdout.write(".");
    await new Promise((r) => setTimeout(r, 10000));
  }
  return null;
}

async function uploadScreenshot(key: string, img: Buffer): Promise<string> {
  const file = new File([img], key, { type: "image/png" });
  const { data, error } = await insforge.storage.from("screenshots").uploadAuto(key, file, {
    upsert: true,
  });
  if (error) throw new Error(`InsForge Storage upload failed: ${JSON.stringify(error)}`);
  return `${process.env.INSFORGE_URL}/storage/object/public/screenshots/${data?.key ?? key}`;
}

function buildDescription(params: {
  summary: AnalyticsSummary;
  devinBody: string;
  beforeUrl: string;
  afterUrl: string | null;
  niaLines: string[];
  files: { filename: string; status: string; additions: number; deletions: number }[];
}): string {
  const { summary, devinBody, beforeUrl, afterUrl, niaLines, files } = params;

  const analyticsTable = [
    "## 📊 Analytics That Triggered This",
    "",
    "| Metric | Value |",
    "|--------|-------|",
    `| Sessions analyzed | ${summary.totalSessions} |`,
    `| Avg. time on page | ${summary.avgTimeOnPage}s |`,
    summary.rageclickElements[0]
      ? `| Top rage-clicked element | \`${summary.rageclickElements[0].element}\` (${summary.rageclickElements[0].count}×) |`
      : null,
    summary.dropOffPoints[0]
      ? `| Avg. scroll depth at drop-off | ${summary.dropOffPoints[0].avgScrollDepth}% on \`${summary.dropOffPoints[0].path}\` |`
      : null,
    summary.exitPaths[0]
      ? `| Top exit path | \`${summary.exitPaths[0].path}\` (${summary.exitPaths[0].count} exits) |`
      : null,
  ]
    .filter(Boolean)
    .join("\n");

  const screenshotSection = [
    "## 🖼️ Visual Changes",
    "",
    "| Before | After |",
    "|--------|-------|",
    `| ![Before — ${PROD_URL}](${beforeUrl}) | ${afterUrl ? `![After — preview](${afterUrl})` : "_Vercel preview still building — check back shortly_"} |`,
  ].join("\n");

  const changeType = (status: string) => {
    if (status === "added") return "➕ Added";
    if (status === "removed") return "🗑️ Removed";
    return "✏️ Modified";
  };

  const filesTable = [
    "## 📂 Files Changed",
    "",
    "| File | Change | +/- |",
    "|------|--------|-----|",
    ...files.map(
      (f) =>
        `| \`${f.filename}\` | ${changeType(f.status)} | +${f.additions} / -${f.deletions} |`
    ),
  ].join("\n");

  const walkthrough = [
    "## 📝 Walkthrough",
    "",
    devinBody.trim(),
  ].join("\n");

  const niaSection = niaLines.length
    ? ["## 🔍 Codebase Context (via Nia)", "", ...niaLines].join("\n")
    : "";

  return [
    analyticsTable,
    "",
    screenshotSection,
    "",
    walkthrough,
    "",
    filesTable,
    "",
    niaSection,
    "",
    "---",
    "_Generated by the UX Agent based on real user behavior data._",
  ]
    .filter((s) => s !== undefined)
    .join("\n");
}

export async function enrichPR(
  sessionCreatedAt: number,
  summary: AnalyticsSummary
): Promise<string> {
  console.log("\n⏳ Waiting for Devin to open a PR");
  const prNumber = await pollForPR(sessionCreatedAt);

  const { data: pr } = await octokit.pulls.get({ owner, repo, pull_number: prNumber });
  const branch = pr.head.ref;

  console.log("\n📸 Taking before screenshot...");
  const beforeImg = await takeScreenshot(PROD_URL);

  console.log("\n⏳ Waiting for Vercel preview");
  const previewUrl = await pollForPreviewUrl(branch);

  let afterImg: Buffer | null = null;
  if (previewUrl) {
    console.log(`\n📸 Taking after screenshot from ${previewUrl}...`);
    afterImg = await takeScreenshot(previewUrl);
  } else {
    console.log("\n⚠️  Preview URL not ready — skipping after screenshot");
  }

  const runKey = `run-${sessionCreatedAt}`;
  const beforeUrl = await uploadScreenshot(`${runKey}/before.png`, beforeImg);
  const afterUrl = afterImg ? await uploadScreenshot(`${runKey}/after.png`, afterImg) : null;

  const { data: changedFiles } = await octokit.pulls.listFiles({
    owner, repo, pull_number: prNumber,
  });

  console.log("\n🔍 Fetching Nia context for changed files...");
  const niaLines: string[] = [];
  for (const file of changedFiles.slice(0, 5)) {
    const ctx = searchCodebase(file.filename);
    if (ctx) {
      niaLines.push(`- **\`${file.filename}\`** — ${ctx.slice(0, 220).replace(/\n/g, " ").trim()}`);
    }
  }

  const newBody = buildDescription({
    summary,
    devinBody: pr.body ?? "",
    beforeUrl,
    afterUrl,
    niaLines,
    files: changedFiles.map((f) => ({
      filename: f.filename,
      status: f.status,
      additions: f.additions,
      deletions: f.deletions,
    })),
  });

  await octokit.pulls.update({ owner, repo, pull_number: prNumber, body: newBody });

  console.log(`✅ PR #${prNumber} description updated`);
  return `https://github.com/${owner}/${repo}/pull/${prNumber}`;
}
